@hostname = 127.0.0.1
@port = 3000
@host = {{hostname}}:{{port}}
@path=api/books
@contentType = application/json

### Get All Book
GET http://{{host}}/{{path}}
Content-Type: {{contentType}}

### Get Book By Id
GET http://{{host}}/{{path}}/6496a4a47b42c236e0507d8a
Content-Type: {{contentType}}

### Post Book
POST http://{{host}}/{{path}}
Content-Type: {{contentType}}

{
    "name": "Bob",
    "salary": 2000,
    "age":35
}

### Put Book By Id
PUT http://{{host}}/{{path}}/6496a4a47b42c236e0507d8a
Content-Type: {{contentType}}

{
    "name": "Mikey",
    "salary": 2001,
    "age":35
}

### Delete Book By Id
DELETE  http://{{host}}/{{path}}/6496a9be91711e8b54654579
Content-Type: {{contentType}}